services:
   postgres:
      image: bitnami/postgresql:latest
      ports: 
        - 5432:5432
      networks:
        - mynet2
      volumes:
        - myvol:/bitnami/postgresql
      environment:
        - POSTGRESQL_USERNAME=myuser
        - POSTGRESQL_PASSWORD=mypass
        - POSTGRESQL_DATABASE=mydb
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U myuser"]
        interval: 5s
        timeout: 5s
        retries: 5
   node:
     image: node:1.0
     env_file:
       - .env
     ports:
       - 3000:3000
     networks:
       - mynet2
     depends_on:
       postgres:
        condition: service_healthy
     build:
       context: .
       dockerfile: Dockerfile
networks:
   mynet2: 
    driver: bridge
volumes:
   myvol:
